sudo: required
language: bash
env:
  global:
#  - USER="hemanth22"
#  - EMAIL="hemanth22hemu@mail.com"
  - REPO="Pre-Release_hemanthindexpage"
  - GH_REPO="github.com/${USER}/${REPO}.git"

before_install:
#  - sudo apt-get -y install gcc make linux-headers-$(uname -r) dkms
#  - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
#  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
#  - sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib" >> /etc/apt/sources.list'
  - sudo apt-get -y update
  - sudo apt-get install -y git
#  - sudo apt-get install -y virtualbox-4.3
#  - VBoxManage -v
#  - sudo apt-get install -q virtualbox --fix-missing
#  - sudo apt-get install -y vagrant
  - sudo apt-get install -y pandoc
  - sudo apt-get install -y acl
  - gem install asciidoctor

script:

 - git clone https://github.com/hemanth22/Development_hemanthindexpage.git
 - git clone https://github.com/hemanth22/Pre-Release_hemanthindexpage.git
 - pwd
 - ls -la
 - getfacl .
 - rm -rf Development_hemanthindexpage/.git
 - ls -la Development_hemanthindexpage
 - ls -la
 - cp -rf Development_hemanthindexpage/* Pre-Release_hemanthindexpage/
 - ls -la
 - rm -rf Development_hemanthindexpage
 - echo "Listing Output after above script"
 - ls -la
 - cd Pre-Release_hemanthindexpage
 - echo "<br/>Prebeta Project Test Link ':' https://hemanth22.github.io/Pre-Release_hemanthindexpage/" >> README.md
 - git remote
 - git config user.email ${EMAIL}
 - git config user.name ${USER}
 - git add .
 - git commit -m "Deployment process using deployer repository from Travis build ':' $TRAVIS_BUILD_NUMBER"
 - git push "https://${GITHUB_API_KEY}@${GH_REPO}" master

after_success:

 - ls -la

notifications:
  slack:
     rooms:
        - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#general
